title: "La Scatola Bianca: Regole Avanzate"
description: Gioco fantasy medievale d'avventura
remote_theme: jekyll-theme-cayman
#aux_links:
#  "La Scatola Bianca su GitHub":
#    - "//github.com/Italian-Translation-Alliance/la-scatola-bianca"
#  "PDF":
#    - "//ita-translation-alliance.itch.io/la-scatola-bianca"
#  "Lulu":
#    - "//www.lulu.com/en/en/shop/alessio-persichetti-and-roberto-bisceglie/la-scatola-bianca/paperback/product-qqj8rn.html?page=1&pageSize=4"
#  "Amazon":  
#    "//www.amazon.it/dp/B096TL8PN3"